### ISSUE TITLE
Cargo install for installing

### ISSUE THREAD

**Issue by Michael-F-Bryan** [joek13/hastebin-client#1]
Just looking at your `README` I notice you tell people to manually copy the compiled binary out of `target/release` and put it somewhere on the `PATH`. Usually you'll use `cargo install` for this because then it'll do everything necessary to install the program on your system.

So installing then turns into

```bash
$ git clone https://github.com/joek13/hastebin-client && cd hastebin-client
$ cargo install
```

Additionally, if you publish this on `crates.io` people can then install it with a single `cargo install hastebin-client`.

**Comment by joek13** [comment]
Honestly, I didn't even know that worked. That's pretty cool. I will update the README to reflect this.

**Comment by Michael-F-Bryan** [comment]
You may need to have `~/.cargo/bin` on your `$PATH`, although if you used rustup to install Rust that should be all done for you.
